[workspace]
resolver = "2"
members = [
  "core"
, "tui"]

[workspace.package]
authors = ["PixelDoted"]

[workspace.dependencies]
# Core
ropey = "1.6"

# Front End
core = { package = "text_editor_core", path = "./core" }

# Tui
ratatui = "0.28"
